services:
  styra-db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-17.5
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      TZ: Asia/Kolkata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./pg_ident.conf:/var/lib/postgresql/data/pg_ident.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - styra-network

volumes:
  pg_data:

networks:
  styra-network:
    external: true