services:
  my-db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-postgres-17.5
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      TZ: Asia/Kolkata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./pg_ident.conf:/etc/postgresql/pg_ident.conf
      - my-pg-data:/var/lib/postgresql/data
      - my-shared-tmp:/data/tmp    # Temporary files like CSV created by exporting SQL result
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - my-network

volumes:
  my-pg-data:
  my-shared-tmp:
    external: true
    name: my-shared-tmp

networks:
  my-network:
    external: true